# Site settings
title: Daniel Yu
email: danielyu742@outlook.com
description: > # keep this and put description below
  Programmer and Audio Designer
url: "https://danielyu.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/daniel-yu-aa4b8420b/"
github_username: dyu1112
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
